services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DATABASE_URL=postgresql://pgadmin:amine123%40@7oumaligue-backend.postgres.database.azure.com:5432/7oumaligue
    command: ["node", "dist/src/server.js"]
    restart: unless-stopped
